### ISSUE TITLE
在windows服务器部署启动失败

### ISSUE THREAD

**Issue by xinghaink** [pacexy/flow#51]
您好，在windows服务器部署启动失败，我是不是忘记配置东西了
![Billfishdyjaef](https://user-images.githubusercontent.com/46272927/203195828-a6a3230f-d7b0-4fd8-be8e-14d2d51a1c69.PNG)

**Comment by pacexy** [comment]
已更新
https://github.com/pacexy/flow#setup-the-environment-variables
